<div class="main">
	<div class="container">
		<div class="userhead">
			<div class="row">
				<div class="col-sm-3 text-center">
					<img src="/images/icons/svg/loop.svg">
					<h6>hongker</h6>
				</div>
				<div class="col-sm-9">
					<div class="userinfo">
						<blockquote>个性基本信息：</blockquote><hr>
						<div class="row">
							<div class="col-sm-12">学校：斯坦福学院</div>
							<div class="col-sm-3 col-xs-6">学历：本科</div>
							<div class="col-sm-9 col-xs-6">年级：2011级</div>
							<div class="col-sm-3 col-xs-6">年龄：20</div>
							<div class="col-sm-3 col-xs-6">年龄：男</div>
							<div class="col-sm-6">邮箱：123456789@qq.com</div>
						</div>
						<blockquote>个性签名：</blockquote><hr>
						<div class="signature">
							<p>生命短暂犹若露珠消散，人们在奔波中探寻答案。</p>
						</div>
						<blockquote>工作时长：3年</blockquote><hr>
						<blockquote>工作经历：</blockquote><hr>
						<div class="experiences">
							<p>在2014年2月～2013年12月，工作地点是华为科技有限公司。</p>
							<p>在2013年1月～2014年1月，工作地点是腾讯有限公司。</p>
							<p>在2012年6月～2013年12月，工作地点是360安全有限公司。</p>
							<p>......</p>
							<p>总共有5段工作经历</p>
						</div>
						<blockquote>技能特长：</blockquote><hr>
						<div class="skills">
							<p>人生真实寂寞入学啊。。。</p>
						</div>
						<blockquote>其他</blockquote><hr>
						<div class="description">
							<p>我个人表示对未来很是向往，你们不要来挡我的路。</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		
	</div>
</div>

