<div class="main">
	<div class="container">

		<div class="userhead">
			<div class="row">
				<div class="col-sm-3">
					<div class="userinfo text-center">
						<img src="/images/icons/svg/loop.svg">
						<h6>hongker</h6>
						<a class="btn btn-success btn-large btn-block" href="/student/edit"><span
							class="fui-new"></span> 编辑信息</a>
					</div>
					<hr>
					<div class="articles">
						<blockquote>我的文章</blockquote>
						<div class="list-group">
							<a href="#" class="list-group-item"> <img
								src="/images/icons/svg/loop.svg" width="50"> Cras justo odio
							</a> <a href="#" class="list-group-item"> <img
								src="/images/icons/svg/loop.svg" width="50"> Cras justo odio
							</a> <a href="#" class="list-group-item"> <img
								src="/images/icons/svg/loop.svg" width="50"> Cras justo odio
							</a>
		
						</div>
						<a class="btn btn-info btn-large btn-block" href="/blog/write"><span class="fui-new"></span> 发表文章</a>
					</div>
				</div>
				<div class="col-sm-9">
					<div class="userinfo">
						<blockquote>个人基本信息：</blockquote>
						
						<div class="row">
							<div class="col-sm-12">学校：斯坦福学院</div>
							<div class="col-sm-3 col-xs-6">学历：本科</div>
							<div class="col-sm-9 col-xs-6">年级：2011级</div>
							<div class="col-sm-3 col-xs-6">年龄：20</div>
							<div class="col-sm-3 col-xs-6">年龄：男</div>
							<div class="col-sm-6">邮箱：123456789@qq.com</div>
						</div>
						<hr>
						<blockquote>个性签名：</blockquote>
						
						<div class="signature indent">
							<p>生命短暂犹若露珠消散，人们在奔波中探寻答案。</p>
						</div>
						<hr>
						<blockquote>工作时长：3年</blockquote>
						<hr>
						<blockquote>工作经历：</blockquote>
						
						<div class="experiences indent">
							<p>在2014年2月～2013年12月，工作地点是华为科技有限公司。</p>
							<p>在2013年1月～2014年1月，工作地点是腾讯有限公司。</p>
							<p>在2012年6月～2013年12月，工作地点是360安全有限公司。</p>
							<p>......</p>
							<p>总共有5段工作经历</p>
						</div>
						<hr>
						<blockquote>技能特长：</blockquote>
						
						<div class="skills indent">
							<p>人生真实寂寞入学啊。。。</p>
						</div>
						<hr>
						<blockquote>其他：</blockquote>
						<div class="description indent">
							<p>我个人表示对未来很是向往，你们不要来挡我的路。</p>
						</div>
						<hr>
						<blockquote>所投意愿：</blockquote>
						<ul class="intentions">
							<li><a href="#">PHP高级工程师 <span class="label label-info">待接纳</span></a></li>
							<li><a href="#">前端工程师</a> <span class="label label-danger">未通过</span></li>
							<li><a href="#">全栈工程师</a> <span class="label label-success">已通过</span></li>
						</ul>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>

