<script src="/js/jquery.bxslider.min.js"></script>
<!-- bxSlider CSS file -->
<link href="/css/jquery.bxslider.css" rel="stylesheet" />
<
<style>
<!--
@media screen and (max-width: 800px) {
	.bxslider li  img {
		height: 150px;
	}
}
-->
</style>
<div class="main">
	<ul class="bxslider">
		<li><img src="/images/slider1.jpeg" /></li>
		<li><img src="/images/slider2.jpeg" /></li>
		<li><img src="/images/slider3.jpeg" /></li>
	</ul>

	<div class="container">
		<div class="row">
			<div class="col-sm-9">
				<div class="row demo-tiles">
					<?php for($i=0;$i<6;$i++):?>
					<div class="col-md-3 col-sm-6 col-xs-12">
						<div class="tile">
							<img src="/images/icons/svg/compas.svg" alt="Compas"
								class="tile-image big-illustration">
							<h3 class="tile-title">Web Oriented</h3>
							<p>I am the bone of my sword.</p>
							<a class="btn btn-primary btn-large btn-block"
								href="http://designmodo.com/flat">查看详情</a>
						</div>
					</div>
					<?php endfor;?>
				</div>
			</div>
			<div class="col-sm-3">
				<div class="input-group ">
					<input type="text" class="form-control" placeholder="搜索内容"
						id="search-query-3"> <span class="input-group-btn">
						<button type="submit" class="btn ">
							<span class="fui-search"></span>
						</button>
					</span>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">

$(document).ready(function(){
	  $('.bxslider').bxSlider({
		  auto: true,
		  controls:false,
	  });
	});

</script>
