<script src="/js/jquery.bxslider.min.js"></script>
<!-- bxSlider CSS file -->
<link href="/css/jquery.bxslider.css" rel="stylesheet" />

<style>
<!--
@media screen and (max-width: 800px) {
	.bxslider li  img {
		height: 150px;
	}
}
-->
</style>
<div class="main">
	<ul class="bxslider">
		<li><img src="/images/slider1.jpeg" /></li>
		<li><img src="/images/slider2.jpeg" /></li>
		<li><img src="/images/slider3.jpeg" /></li>
	</ul>

	<div class="container">

		<div class="row">
			<div class="col-sm-9">
				<blockquote>求职ing</blockquote>
				<hr>
				<div class="row demo-tiles">
					<?php for($i=0;$i<6;$i++):?>
					<div class="col-md-4 col-sm-6 col-xs-12">
						<div class="tile">
							<img src="/images/icons/svg/compas.svg" alt="Compas"
								class="tile-image big-illustration">
							<h3 class="tile-title">Web Oriented</h3>
							<p>I am the bone of my sword.</p>
							<a class="btn btn-primary btn-large btn-block"
								href="/student/info/1">查看详情</a>
						</div>
					</div>
					<?php endfor;?>
				</div>

				<blockquote>实习ing</blockquote>
				<hr>
				<div class="row demo-tiles">
					<?php for($i=0;$i<6;$i++):?>
					<div class="col-md-4 col-sm-6 col-xs-12">
						<div class="tile">
							<img src="/images/icons/svg/compas.svg" alt="Compas"
								class="tile-image big-illustration">
							<h3 class="tile-title">Web Oriented</h3>
							<p>I am the bone of my sword.</p>
							<a class="btn btn-primary btn-large btn-block"
								href="http://designmodo.com/flat">查看详情</a>
						</div>
					</div>
					<?php endfor;?>
				</div>
			</div>
			<div class="col-sm-3">
				<div class="tile">
					<img src="/images/icons/svg/loop.svg" alt="Compas"
						class="tile-image big-illustration"> <a href="/student/home"
						class="btn btn-block btn-lg btn-danger"><span class="fui-home"></span>
						个人中心</a>
				</div>

				<blockquote>工作达人</blockquote>
				<hr>
				<div class="list-group">
					<a href="#" class="list-group-item"> <img
						src="/images/icons/svg/loop.svg" width="50"> Cras justo odio
					</a> <a href="#" class="list-group-item"> <img
						src="/images/icons/svg/loop.svg" width="50"> Cras justo odio
					</a> <a href="#" class="list-group-item"> <img
						src="/images/icons/svg/loop.svg" width="50"> Cras justo odio
					</a>

				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">

$(document).ready(function(){
	  $('.bxslider').bxSlider({
		  auto: true,
		  controls:false,
	  });
	});

</script>
