<div class="main">
	<div class="container">
		<div class="row">
			<div class="col-sm-9">
				<div class="page-header text-center">
					<h6><?php echo $article->title?></h6>
				</div>
				<div class="digest">
					<small><strong>摘要：</strong><?php echo $article->digest?></small>
				</div>
				<div class="content">
					<?php echo $article->content?>
				</div>
			</div>
		</div>
	</div>
</div>

