<div class="main">
	<div class="container">
		<blockquote>发表文章</blockquote>
		<form class="form-horizontal" role="form">
			<div class="form-group">
				<label for="title" class="col-sm-2 control-label">文章标题</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="title"
						placeholder="请填入文章的标题">
				</div>
			</div>
			<div class="form-group">
				<label for="" class="col-sm-2 control-label">封面图片</label>
				<div class="col-sm-8">
					<input type="file" class="filestyle" name="file" data-input="false" data-buttonName="btn-info" data-buttonText=" 选择图片 ">
					<p class="help-block">请选择一张图片作为封面</p>
				</div>
			</div>
			<div class="form-group">
				<label for="inputPassword3" class="col-sm-2 control-label">文章内容</label>
				<div class="col-sm-10">
					<script type="text/plain" id="myEditor" style="width: 1000px; height: 240px;">
   						 在这里编辑文章内容
					</script>
					<script type="text/javascript">
					    //实例化编辑器
					    var um = UM.getEditor('myEditor');
					</script>
				</div>
			</div>
			
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-primary">发布文章</button>
				</div>
			</div>
		</form>

	</div>
</div>