<div class="header">
	<i class="logo icon-twitter"></i>
	<h1>To be or not to be, that's a question</h1>
	<p>
		I am the bone of my sword <br> Steel is my body<br> Fire is my blood <br>
		I have created over a thousand blades <br> Unknown to Death<br> Nor
		known to Life
	</p>
</div>
<div class="container">
	<div class="content">
		<blockquote>最新岗位</blockquote>
		<hr>
		<div class="row">
			<div class="row">
				<?php for($i=0;$i<6;$i++):?>
				<div class="col-sm-4">
					<div class="palette palette-peter-river">经营管理类（221个职位）</div>
					<ul class="job-list">
						<li><small>北京</small> <small class="job">产品研发设计</small> <small
							class="date">5月</small></li>
						<li><small>成都</small> <small class="job">全栈工程师</small> <small
							class="date">10月</small></li>
					</ul>
				</div>
				<?php endfor;?>
			</div>
		</div>

		<blockquote>求职ing</blockquote>
		<hr>
		<div class="row demo-tiles">
			<?php for($i=0;$i<6;$i++):?>
			<div class="col-md-3 col-sm-6 col-xs-12">
				<div class="tile">
					<img src="/images/icons/svg/compas.svg" alt="Compas"
						class="tile-image big-illustration">
					<h3 class="tile-title">Web Oriented</h3>
					<p>I am the bone of my sword.</p>
					<a class="btn btn-primary btn-large btn-block"
						href="http://designmodo.com/flat">查看详情</a>
				</div>
			</div>
			<?php endfor;?>
		</div>
	</div>
</div>
<div class="join">
	
</div>