<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo \Phalcon\Tag::getTitle(); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Loading Bootstrap -->
	<link rel="stylesheet" type="text/css" href="/css/vendor/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/css/flat-ui.min.css">
    <link rel="stylesheet" type="text/css" href="/css/admin.css">


    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script type="text/javascript" src="/js/vendor/html5shiv.js"></script>
      <script type="text/javascript" src="/js/vendor/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="login-bg">
  	<!-- container -->
   	<div class="login-main login-form ">
   		<form class="form-body" method="post" action="/admin/login/auth">
   		<p class="text-center login-header">欢迎登录管理平台</p>
		<div class="form-group">
			<input class="form-control login-field" value="" placeholder="请输入用户名" name="name" type="text">
			<label class="login-field-icon fui-user" for="login-name"></label>
		</div>
		
		<div class="form-group">
			<input class="form-control login-field" value="" placeholder="请输入密码" name="pass" type="password">
			<label class="login-field-icon fui-lock" for="login-pass"></label>
		</div>
		<div class="form-group text-center">
			<?php $this->flashSession->output() ?>
		</div>
		<input type="hidden" name="<?php echo $this->security->getTokenKey() ?>"
        value="<?php echo $this->security->getToken() ?>"/>
		<button class="btn btn-info btn-lg btn-block" type="submit" >登 录</button>
		</form>
   	</div>
    <!-- /.container -->

    <!-- jQuery (necessary for Flat UI's JavaScript plugins) -->
    <script type="text/javascript" src="/js/vendor/jquery.min.js"></script>
    <script type="text/javascript" src="/js/vendor/video.js"></script>
    <script type="text/javascript" src="/js/flat-ui.min.js"></script>
    <script type="text/javascript" src="/js/application.js"></script>
  </body>
</html>


