<div class="footer">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-6  row">
				<div class="col-sm-4 col-xs-12 col-md-3 clearfix">
					<h1 class="foot-header">关于我们</h1>
					<ul class="about">
						<li><a href="/index/map">站点地图</a></li>
						<li><a href="/index/suggest">意见反馈</a></li>
						<li><a href="/index/disclaimer">免责声明</a></li>
						<li><a href="/index/about">关于我们</a></li>
					</ul>
				</div>
				<div class="col-sm-8 col-xs-12 col-md-9 clearfix">
					<h1 class="foot-header">合作伙伴</h1>
					<ul class="hb">
						<li><a href="/index/map">Bootstrap</a></li>
						<li><a href="/index/map">Phalcon</a></li>
						<li><a href="/index/map">......</a></li>
					</ul>
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 row">
				<div class="col-sm-12 col-xs-12 attention">
					<h1 class="foot-header">关注我们</h1>
					<ul>
						<li><a href="#"><i class=" icon-rss icon-large"></i></a></li>
						<li><a href="#"><i class=" icon-twitter icon-large"></i></a></li>
						<li><a href="#"><i class="icon-phone icon-large"></i></a></li>
					</ul>
					<div class="col-xs-12 copyright">
							Copyright © hongker AllRight Reserved<br>
							版权所有 复制必究
					</div>
				</div>
				
			</div>
			
		</div>
	</div>
</div>