 <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
          </button>
          <a class="navbar-brand" href="#">Platform</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li <?php if($controller=='index'):?> class="active"<?php endif;?>><a href="/index">首页</a></li>
            <li <?php if($controller=='student'):?> class="active"<?php endif;?>><a href="/student">学生</a></li>
            <li <?php if($controller=='company'):?> class="active"<?php endif;?>><a href="/company">公司<span class="navbar-unread"></span></a></li>
            <li <?php if($controller=='about'):?> class="active"<?php endif;?>><a href="/about">关于我们</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          <?php if($this->session->has('id')):?>
          	<li class="dropdown">
                  <a href="#" class="dropdown-toggle active" data-toggle="dropdown"><?php echo $this->session->get('username')?> <b class="caret"></b></a>
                  <span class="dropdown-arrow"></span>
                  <ul class="dropdown-menu">
                    <li><a href="#">个人信息</a></li>
                    <li class="divider"></li>
                    <li><a href="/login/logout">退 出</a></li>
                  </ul>
                </li>
          <?php else:?>
            <li ><a href="/login">登录</a></li>
            <li <?php if($controller=='register'):?> class="active"<?php endif;?>><a href="/register">注册</a></li>
          <?php endif;?>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
