 <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
          </button>
          <a class="navbar-brand" href="#">Platform</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/index">首页</a></li>
            <li><a href="/about">学生</a></li>
            <li><a href="/about">公司</a></li>
            <li><a href="/about">关于我们</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li ><a href="/login">登录</a></li>
            <li><a href="/register">注册</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
