<div class="container">
	<div class="row register">
		<div class="col-sm-4 col-xs-12">
			<div class="icon">
				<img src="/images/icon.png" alt="Welcome to Mail App">
				<h4>
					Welcome to <small>Platform</small>
				</h4>
			</div>
		</div>
		<div class="col-sm-6 col-xs-12">
			<div class="login-form">
				<ul id="registerTab" class="nav nav-tabs" role="tablist">
					<li role="presentation" class="active"><a href="#student"
						id="student-tab" role="tab" data-toggle="tab"
						aria-controls="student" aria-expanded="true">学生</a></li>
					<li class="" role="presentation"><a aria-expanded="false"
						href="#company" role="tab" id="company-tab" data-toggle="tab"
						aria-controls="company">企业</a></li>

				</ul>
				<div id="myTabContent" class="tab-content">
					<div role="tabpanel" class="tab-pane fade active in" id="student"
						aria-labelledby="student-tab">
						<form class="" method="post" action="/register/addStudent">
							<div class="form-group">
								<input class="form-control login-field" autofocus
									placeholder="请填入一个用户名" name="name" type="text"> <label
									class="login-field-icon fui-user" for="name"></label>
							</div>
							<div class="form-group">
								<input class="form-control login-field" placeholder="请填入您的邮箱"
									name="email" type="email"> <label
									class="login-field-icon fui-mail" for="email"></label>
							</div>

							<div class="form-group">
								<input class="form-control login-field" placeholder="请填写密码"
									name="pass" type="password"> <label
									class="login-field-icon fui-lock" for="pass"></label>
							</div>
							<div class="form-group text-center">
								<?php $this->flashSession->output()?>
							</div>
							<input type="hidden"
								name="<?php echo $this->security->getTokenKey() ?>"
								value="<?php echo $this->security->getToken() ?>" />

							<button class="btn btn-success btn-lg btn-block" type="submit">注
								册</button>

						</form>
					</div>
					<div role="tabpanel" class="tab-pane fade" id="company"
						aria-labelledby="company-tab">
						<form class="" method="post" action="/register/addManager">
							<div class="form-group">
								<input class="form-control login-field" autofocus
									placeholder="请填入一个用户名" name="name" type="text"> <label
									class="login-field-icon fui-user" for="name"></label>
							</div>
							<div class="form-group">
								<input class="form-control login-field" placeholder="请填入您的邮箱"
									name="email" type="email"> <label
									class="login-field-icon fui-mail" for="email"></label>
							</div>

							<div class="form-group">
								<input class="form-control login-field" placeholder="请填写密码"
									name="pass" type="password"> <label
									class="login-field-icon fui-lock" for="pass"></label>
							</div>
							<div class="form-group text-center">
								<?php $this->flashSession->output()?>
							</div>
							<input type="hidden"
								name="<?php echo $this->security->getTokenKey() ?>"
								value="<?php echo $this->security->getToken() ?>" />

							<button class="btn btn-success btn-lg btn-block" type="submit">注
								册</button>

						</form>
					</div>

				</div>
			</div>


		</div>
	</div>
</div>