<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Platform</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Loading Bootstrap -->
	<link rel="stylesheet" type="text/css" href="/css/vendor/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/css/flat-ui.min.css">
    <link rel="stylesheet" type="text/css" href="/css/common.css">
	<link rel="stylesheet" type="text/css" href="/css/font-awesome.min.css">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script type="text/javascript" src="/js/vendor/html5shiv.js"></script>
      <script type="text/javascript" src="/js/vendor/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="/js/vendor/jquery.min.js"></script>
    <script type="text/javascript" src="/js/vendor/video.js"></script>
    <script type="text/javascript" src="/js/flat-ui.min.js"></script>
    <script type="text/javascript" src="/js/application.js"></script>
    <script type="text/javascript" src="/js/unslider.min.js"></script>
  </head>
  <body>
  	<!-- container -->
   	<?php echo $this->getContent() ?>
    <!-- /.container -->

    <!-- jQuery (necessary for Flat UI's JavaScript plugins) -->
    
  </body>
</html>


