<script src="/js/jquery.bxslider.min.js"></script>
<!-- bxSlider CSS file -->
<link href="/css/jquery.bxslider.css" rel="stylesheet" />
<
<style>
<!--
@media screen and (max-width: 800px) {
	.bxslider li  img {
		height: 150px;
	}
}
-->
</style>
<div class="main">
	<div class="desc">
		<div class="content">
			<h1>Nor known to Life  </h1>
			<a href="#" class="btn btn-lg btn-info">WELCOME TO JOIN US</a>
		</div>
		
	</div>
	<div class="container">
		<div class="content">
			<div class="row">
				<div class="text-right">
					<div class="citys">
						<small>城市：</small>
						<small><a class="text-info" href="">[全部]</a></small>
						<small><a class="text-info" href="">北京</a></small>
						<small><a class="text-info" href="">上海</a></small>
						<small><a class="text-info" href="">广州</a></small>
						<small><a class="text-info" href="">深圳</a></small>
						<small><a class="text-info" href="">成都</a></small>
						<small><a class="text-info" href="">杭州</a></small>
						<small class="other">
							<div class="btn-group">
								<a class="text-info" data-toggle="dropdown">其他<span class="caret">
								<ul class="dropdown-menu "  role="menu">
	    							<li><a href="#">南京</a></li>
	    							<li><a href="#">天津</a></li>
	    							<li><a href="#">重庆</a></li>
	    						</ul>
							</div>
						</small>
					</div>
				</div>
			</div>
		</div>
		<div class="lists">
			<div class="class1">
				<blockquote>推荐企业</blockquote>
				<div class="row">
				<?php for($i=0;$i<5;$i++):?>
					<div class="col-sm-3 text-center">
						<img class="img-responsive" src="/images/hp.png" />
						<p>this is company description</p>
					</div>
				<?php endfor;?>
				</div>
			</div>
			<div class="class2">
				<blockquote>推荐岗位</blockquote>
				<div class="row">
				<?php for($i=0;$i<6;$i++):?>
					<div class="col-sm-4">
						<div class="palette palette-concrete">
							经营管理类（221个职位）
						</div>
						<ul class="job-list">
							<li>
								<small>北京</small>
								<small class="job">产品研发设计</small>
								<small class="date">5月</small>
							</li>
							<li>
								<small>成都</small>
								<small class="job">全栈工程师</small>
								<small class="date">10月</small>
							</li>
						</ul>
					</div>
				<?php endfor;?>
				</div>
			</div>
			<div class="class3">
				<blockquote>热门行业</blockquote>
				<div class="row">
				<?php for($i=0;$i<6;$i++):?>
					<div class="col-sm-4">
						<h6>
							<a href="">互联网</a>
						</h6>
						<ul class="job-list">
							<li>
								<small>百度 | </small>
								<small class="job">产品研发设计</small>
								<small class="job">前端设计师</small>
								<small class="job">前端设计师</small>
							</li>
							<li>
								<small>腾讯 | </small>
								<small class="job">全栈工程师</small>
								<small class="job">Java程序员</small>
							</li>
						</ul>
					</div>
				<?php endfor;?>
				</div>
			</div>
		</div>
	</div>
	<ul class="bxslider">
		<li><img src="/images/slider1.jpeg" /></li>
		<li><img src="/images/slider2.jpeg" /></li>
		<li><img src="/images/slider3.jpeg" /></li>
	</ul>

	<div class="container">
		company
	</div>
</div>

<script type="text/javascript">

$(document).ready(function(){
	  $('.bxslider').bxSlider({
		  auto: true,
		  controls:false,
	  });
	});

</script>
