<div class="main">
	<div class="company-info">
		<div class="container">
			<div class="row">
				<div class="col-sm-3 col-xs-12 company-logo">
					<img alt="logo" class="" src="<?php echo $company->logo?>">
				</div>
				<div class="col-sm-9">
					<h5><?php echo $company->name?></h5>
					<small> 规模：10000人以上 性质：中外合营(合资·合作) 所在地：北京 </small><br>
					<button class="btn btn-embossed btn-sm btn-danger">
						<span class="fui-plus"></span> 关 注
					</button>
				</div>
			</div>
			<div class="description">
				<small><?php echo $company->description?></small>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-sm-9">
				<blockquote>目标职位：</blockquote>
				<h6 class="indent">PHP高级工程师</h6>
				<hr>
				<blockquote>填写意愿：</blockquote>
				<form class="form-horizontal" method="post"
					action="/company/postIntention">
					<div class="form-group">
						<div class="col-sm-12">
							<script type="text/plain" id="myEditor" style="height: 240px;">
    							<p>在这里输入内容</p>
							</script>
							<script type="text/javascript">
							    //实例化编辑器
							    var um = UM.getEditor('myEditor',{
							    	initialFrameWidth:"100%",
							        });
							</script>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-12">
							<label class="radio"> <input class="custom-radio"
								name="optionsRadios" id="optionsRadios1" value="option1"
								data-toggle="radio" type="radio" checked="true"><span
								class="icons"><span class="icon-unchecked"></span><span
									class="icon-checked"></span></span> 允许该公司查看你的履历，这样可以增加应聘成功机率。
							</label>
						</div>
					</div>
					<div class="form-group">
						<div class=" col-sm-10">
							<button type="submit" class="btn btn-primary">提交意愿</button>
						</div>
					</div>
				</form>

			</div>
			<div class="col-sm-3"></div>
		</div>

	</div>


</div>

