<div class="main job">
	<div class="container job-info">
		<div class="row">
			<div class="col-sm-8">
				<div class="contents">
					<div class="palette palette-peter-river">
						<h4>PHP工程师</h4>
						<small class="img-comment">惠普科技有限公司</small>
					</div>
					<div class="row">
						<div class="col-sm-8">
							<div class="job-desc">
								<h4 class="salary">9-12万</h4>
								<p>
									<span>成都-高新区</span> | <span>本科</span> | <span>1年经验</span>
								</p>
								<p class="date">发布时间：2014-12-29</p>
								<p class="description text-info">发展空间大，气氛融洽</p>
							</div>
						</div>
						<div class="col-sm-4">
							<a class="btn btn-danger btn-embossed btn-lg  intent-btn"
								href="/company/intent/1"> <span class="fui-plus"></span>我感兴趣，投递意愿
							</a>
						</div>
					</div>
					<blockquote>基本信息</blockquote>
					<div class="base-info">
						<div class="row">
							<div class="col-sm-6">
								<small>工作地点:<span class="address">成都-高新区</span></small>
							</div>
							<div class="col-sm-6">
								<small>所属部门:<span class="department">技术部</span></small>
							</div>
						</div>
					</div>
					<blockquote>职位描述</blockquote>
					<div class="job-description">
						<p>有上进心，不怕吃苦</p>
						<p>有纪律</p>
					</div>
					<blockquote>岗位要求</blockquote>
					<div class="job-condition">
						<div class="row">
							<div class="col-sm-6">
								<small class="key">学历要求：</small> <small class="value">本科</small>
							</div>
							<div class="col-sm-6">
								<small class="key">性别要求：</small> <small class="value">不限</small>
							</div>
							<div class="col-sm-6">
								<small class="key">专业要求：</small> <small class="value">不限</small>
							</div>
							<div class="col-sm-6">
								<small class="key">语言要求：</small> <small class="value">普通话</small>
							</div>
							<div class="col-sm-6">
								<small class="key">工作年限：</small> <small class="value">1年以上</small>
							</div>
							<div class="col-sm-6">
								<small class="key">年龄要求：</small> <small class="value">20-45</small>
							</div>
						</div>
					</div>
					<blockquote>公司介绍:</blockquote>
					<div class="company">
						惠普（HP）公司成立于1939年，是一家业务运营遍及全球170多个国家和地区的高科技公司。我们致力于探索科技和服务如何帮助人们和企业解决其遇到的问题和挑战，并把握机遇、实现愿景、成就梦想。我们运用新的思想和理念来打造更简单、更有价值、更值得信赖的技术体验，不断帮助客户改善其生活和工作方式。
					</div>
				</div>
			</div>
			<div class="col-sm-4">
				<div class="contents">
					<blockquote>岗位发布公司</blockquote>
					<div class="company row">
						<div class="col-sm-12">
							<a href="/company/detail/1"><img src="/images/hp.png"></a>
						</div>
						<div class="col-sm-12">
							<p>惠普科技有限公司</p>
						</div>
						<div class="col-sm-12">
							<small class="key">行业：</small> <small class="value">计算机，互联网</small>
						</div>
						<div class="col-sm-12">
							<small class="key">规模：</small> <small class="value">10000人以上</small>
						</div>
						<div class="col-sm-12">
							<small class="key">性质：</small> <small class="value">外企</small>
						</div>
						<div class="col-sm-12">
							<small class="key">地址：</small> <small class="value">北京市朝阳区建国路112号中国惠普大厦(近招商局大厦)</small>
						</div>
					</div>
					<div class="media">
						<a class="media-left" href="#"> <img data-holder-rendered="true"
							src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjE0LjUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg=="
							style="width: 64px; height: 64px;" class="media-object"
							data-src="holder.js/64x64" alt="64x64">
						</a>
						<div class="media-body talk">
							<span></span>
							<p>您好，我是南京惠高智能科技有限公司招聘负责人，很高兴认识您，有任何问题欢迎交流沟通</p>
						</div>
					</div>
					<div class="message">
						<form role="form">
							<div class="form-group">
								<label for="content"><i class="icon-comment-alt"></i> 给我留言</label>
								<textarea class="form-control" rows="2" name="content"
									placeholder="请输入您想咨询的问题，我讲及时为您解答"></textarea>
							</div>
							<div class="form-group text-right">
								<button type="submit" class="btn btn-info btn-sm">发送</button>
							</div>
						</form>
					</div>
					<blockquote>其他机会</blockquote>
					<div class="list-group">
						<a href="#" class="list-group-item"> <img
							src="/images/icons/svg/loop.svg" width="50"> Cras justo odio
						</a> <a href="#" class="list-group-item"> <img
							src="/images/icons/svg/loop.svg" width="50"> Cras justo odio
						</a> <a href="#" class="list-group-item"> <img
							src="/images/icons/svg/loop.svg" width="50"> Cras justo odio
						</a>
	
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

